name: Build

on:
  push:
    branches: [ "master" ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04, target: linux-x64, platform: linux-x64 }
          - { os: ubuntu-20.04, target: linux-arm64, platform: linux-x64 }
          - { os: macos-latest, target: osx-x64, platform: darwin-x64 }
          - { os: macos-latest, target: osx-arm64, platform: darwin-arm64 }
          - { os: windows-latest, target: win-x64, platform: win32-x64}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        pre-release: true
    - name: Build-General
      if: matrix.target != 'linux-arm64'
      run: dotnet publish EmmyLua.LanguageServer -r ${{ matrix.target }} -c Release -o ${{ github.workspace }}/artifact/${{ matrix.platform }} --sc /p:DebugType=None
    - name: Build-Linux-Arm64
      if: matrix.target == 'linux-arm64'
      run: | 
        dotnet tool install --global dotnet-cross
        dotnet cross publish EmmyLua.LanguageServer -r linux-arm64 -c Release -o ${{ github.workspace }}/artifact/${{ matrix.platform }} --sc /p:DebugType=None
    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        name: EmmyLua.LanguageServer-${{ matrix.platform }}
        path: ${{ github.workspace }}/artifact/

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download
      uses: actions/download-artifact@v2
    - name: zip win32-x64
      uses: TheDoctor0/zip-release@v0.2.1
      with:
        filename: EmmyLua.LanguageServer-win32-x64.zip
        path: EmmyLua.LanguageServer-win32-x64
    - name: tar linux-x64
      run: |
        chmod +x EmmyLua.LanguageServer-linux-x64/EmmyLua.LanguageServer
        tar -czf EmmyLua.LanguageServer-linux-x64.tar.gz -C EmmyLua.LanguageServer-linux-x64 .

    - name: tar linux-arm64
      run: |
        chmod +x EmmyLua.LanguageServer-linux-arm64/EmmyLua.LanguageServer
        tar -czf EmmyLua.LanguageServer-linux-arm64.tar.gz -C EmmyLua.LanguageServer-linux-arm64 .

    - name: zip darwin-x64
      uses: TheDoctor0/zip-release@v0.2.1
      with:
        filename: EmmyLua.LanguageServer-darwin-x64.zip
        path: EmmyLua.LanguageServer-darwin-x64
    - name: zip darwin-arm64
      uses: TheDoctor0/zip-release@v0.2.1
      with:
        filename: EmmyLua.LanguageServer-darwin-arm64.zip
        path: EmmyLua.LanguageServer-darwin-arm64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: EmmyLuaAnalyzer
        draft: false
        generate_release_notes: true
        files: |
          EmmyLua.LanguageServer-linux-x64.zip
          EmmyLua.LanguageServer-darwin-x64.zip
          EmmyLua.LanguageServer-darwin-arm64.zip
          EmmyLua.LanguageServer-win32-x64.zip
        token: ${{ secrets.RELEASE }}
