name: Build

on:
  push:
    branches: [ "master" ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, target: linux-x64, platform: linux-x64 }
          - { os: macos-latest, target: osx-x64, platform: darwin-x64 }
          - { os: macos-latest, target: osx-arm64, platform: darwin-arm64 }
          - { os: windows-latest, target: win-x64, platform: win32-x64}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet publish LanguageServer -r ${{ matrix.target }} -c Release -o ${{ github.workspace }}/artifact/${{ matrix.platform }}
    - name: Upload
      uses: actions/upload-artifact@v3
      with: 
        name: ${{ matrix.platform }}
        path: ${{ github.workspace }}/artifact/

  check:
    runs-on: ubuntu-latest
    outputs:
      isTag: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Check if tag
        id: check
        run: echo "Is tag: ${{ startsWith(github.ref, 'refs/tags/') }}"
  publish:
    runs-on: ubuntu-latest
    needs: [build, check]
    if: needs.check.outputs.isTag == 'true'
    strategy:
      matrix:
        platform: [ win32-x64, linux-x64, darwin-x64, darwin-arm64]
    steps:
    - name: Download
      uses: actions/download-artifact@v2
    - name: zip ${{ matrix.platform }}
      uses: TheDoctor0/zip-release@v0.2.1
      with:
        filename: ${{ matrix.platform }}.zip
        path: ${{ matrix.platform }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: EmmyLuaAnalyzer
        draft: false
        generate_release_notes: true
        files: |
          linux-x64.zip
          darwin-x64.zip
          darwin-arm64.zip
          win32-x64.zip
        token: ${{ secrets.RELEASE }}
